### About:
4/11/2021 Program calculate the correlation coefficient: => TBD

    (1) between internet speeds
    (2) between states
    (3) between states & internet speeds??? -> Self Assigned

#### NOTE: Make sure to unzip the xlsx files

@author: Minh Nguyen @AIA

@credit: Qasim, Andrei @AIA

In [7]:
import numpy as np
from numpy.random import randn
from numpy.random import seed
from numpy import array_split
import pandas as pd
from sklearn import metrics as mt
from sklearn import model_selection as md
from matplotlib import pyplot as plt
import seaborn as sns
import sklearn.datasets as ds
import random

### Correlation Calculation

In [8]:
def correlation_cal(df):
    # Instead of just dropping the missing values, we will fill in N/A values
    if df.isna().values.any():
        while True:
            missing_type = input("Please enter the type of missing value replacement: mean, medium, mode, or drop from the row")
            missing_type = missing_type.lower()
            if(missing_type in ['mean', 'median', 'mode', 'drop']):
                if(missing_type == 'mean'):
                    df.fillna(df.mean(), inplace=True)
                elif(missing_type == 'median'):
                    df.fillna(df.median(), inplace=True)
                elif(missing_type == 'mode'):
                    df.fillna(df.mode(), inplace=True)
                else:
                    df.dropna()
                break
            else:
                print("Please input the option from the list")
    
    # Calculate input data correlation
    while True:
        corr_type = input("Please enter type of correlation: Pearson, Spearman, or Kendall: ")
        corr_type = corr_type.lower()
        if corr_type in ['pearson', 'spearman', 'kendall']:
            break
        else:
            print("Please try again")
    
    # Plot correlation matrix
    corrMatrix = df.corr(method=corr_type)
    _, ax = plt.subplots(figsize=(12, 10))
    sns.heatmap(corrMatrix, ax = ax, cmap="gray", linewidths = 0.1) # cmap can also be "YlGnBu"

#### Preprocess Data

In [9]:
!ls

Correlation - Fixed BB 3.ipynb
fixed_bb_2017.csv

In [10]:
def parse_data(file):
    """ Function load csv file into csd pandas """
    dataset = pd.read_csv(file)
    return dataset

In [11]:
df = parse_data("fixed_bb_2017.csv")

In [12]:
df

,Unnamed: 0,logrecno,provider_id,frn,providername,dbaname,holdingcompanyname,hoconum,hocofinal,stateabbr,blockcode,techcode,consumer,maxaddown,maxadup,business
0,0,5954953,55574,3768165,"COMCAST CABLE COMMUNICATIONS, LLC",Comcast,Comcast Corporation,130317,Comcast Corporation,CA,60816062002014,43,1,987.0,35.0,1
1,1,22859880,57164,21235379,Blu Sky Wireless,Blu Sky Wireless,Blu Sky Wireless,260004,Blu Sky Wireless,OH,391354550025013,70,1,25.0,5.0,1
2,2,68924581,54694,12369286,"HNS License Sub, LLC",HughesNet,"Hughes Network Systems, LLC",130627,"Hughes Network Systems, LLC",TX,484119502001559,60,1,25.0,3.0,1
3,3,53911095,54694,12369286,"HNS License Sub, LLC",HughesNet,"Hughes Network Systems, LLC",130627,"Hughes Network Systems, LLC",MD,240299505001059,60,1,25.0,3.0,1
4,4,64392495,55262,18756155,"VSAT Systems, LLC",Skycasters,"VSAT Systems, LLC",300167,"VSAT Systems, LLC",OR,410019506001033,60,1,2.0,1.3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,310132,53920,21701891,AMG Technology Investment Group,Nextlink Residential,AMG Technology Investment Group LLC,290010,AMG Technology Investment Group LLC,TX,480970001003175,70,1,50.0,10.0,1
996,996,7632851,55592,17851569,One Point Technologies Inc.,One Point Technologies Inc.,"Blue Valley Tele-Communications, Inc.",130144,"Blue Valley Tele-Communications, Inc.",KS,202019786001109,70,1,25.0,3.0,1
997,997,65718765,55262,18756155,"VSAT Systems, LLC",Skycasters,"VSAT Systems, LLC",300167,"VSAT Systems, LLC",PA,421010284004002,60,1,2.0,1.3,1
998,998,64940929,59349,1568880,GCI Communication Corp.,GCI Communication Corp.,GCI Holdings LLC,130534,GCI Holdings LLC,PA,421179509002208,60,0,0.0,0.0,1
999,999,27276314,58623,25646373,"Charter Communications, Inc.",Charter Communications Inc,Charter Communications,130235,Charter Communications,NY,360930210023001,43,1,940.0,35.0,1